name = "CartesianCategories"
uuid = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"
authors = [
	"Mohamed Barakat <mohamed.barakat@uni-siegen.de>",
	"Fabian Zickgraf <f.zickgraf@dashdos.com>",
	"Tom Kuhmichel <tom.kuhmichel@student.uni-siegen.de>"
]

# Transpiled from GAP's CartesianCategories v2025.08-01
version = "0.3.11"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
MonoidalCategories = "bfd98c86-782f-4b94-909f-74167f1eb613"

[weakdeps]

[extensions]

[compat]
julia = "1.11"
CAP = "0.4, 0.5, 0.6"
MonoidalCategories = "~0.2.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
