name = "CartesianCategories"
uuid = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"
authors = [
	"Mohamed Barakat <mohamed.barakat@uni-siegen.de>",
	"Tom Kuhmichel <tom.kuhmichel@student.uni-siegen.de>",
	"Fabian Zickgraf <fabian.zickgraf@uni-siegen.de>",
]
version = "0.1.1"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"

[compat]
julia = "1.11"
CAP = "0.1, 0.2"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
